/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ayulit' at '12/31/16 5:57 PM' with Gradle 2.14.1
 *
 * @author ayulit, @date 12/31/16 5:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
